---
- hosts: all
  become: yes
  tasks: 
        - name: Install jdk8
          apt:
              name: openjdk-8-jre
              state: present 
          when: ansible_os_family=="Debian"
              
