---
- hosts: all
  become: yes
  tasks: 
        - name: Install jdk8
          apt:
              name: openjdk-8-jre
              state: present 
          when: ansible_os_family=="Debian"

        - name: Install jdk8 redhat
          yum:
              name: java-1.8.0-openjdk
              state: present 
          when: ansible_os_family=="RedHat"      
