---
- name: Create new tomcat group
  group:
      name: tomcat
      state: present

- name: Create a tomcat user
  user:
   name: tomcat
   groups: tomcat
   shell: /bin/false
   home: /opy/tomcat
   state: present
