---
# tasks file for mytomcatrole
    - include_tasks : InstallJava.yml
    - include_tasks : CreateTomcatUser.yml
    - include_tasks : InstallTomcat.yml
    - include_tasks : UpdatePermissions.yml
    - include_tasks : CreateSystemdServiceFile.yml
    - include_tasks : TomcatServiceStart.yml